---

- name: Create configuration in {{leutils_config_file}}
  lineinfile: >
    dest="{{leutils_config_file}}"
    regexp="{{item.regexp}}"
    line="{{item.line}}"
    backup="yes"
    create="yes"
    owner="{{leutils_config_file_owner}}"
    group="{{leutils_config_file_group}}"
    mode="{{leutils_config_file_mode}}"
  with_items:
    - { regexp: "^WEBSERVER=", line: "WEBSERVER=\"{{leutils_config_WEBSERVER}}\""}
  tags: config_lectl

# EOF
...
