---

- name: "config: Create configuration in {{ leutils_config_file }}"
  lineinfile:
    dest: "{{ leutils_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: "{{ leutils_owner }}"
    group: "{{ leutils_group }}"
    mode: "{{ leutils_config_mode }}"
    backup: yes
    create: yes
  with_items:
    - { regexp: "^WEBSERVER=", line: "WEBSERVER=\"{{ leutils_config_WEBSERVER }}\""}
    - { regexp: "^LEROOT=", line: "LEROOT=\"{{ leutils_config_LEROOT }}\""}
    - { regexp: "^FINGERPRINTFILE=", line: "FINGERPRINTFILE=\"{{ leutils_config_FINGERPRINTFILE }}\""}

- name: "config: Create directory {{ leutils_config_LEROOT }}"
  file:
    state: "directory"
    path: "{{ leutils_config_LEROOT }}"
    owner: "{{ leutils_owner }}"
    group: "{{ leutils_group }}"
    mode: "{{ leutils_LEROOT_mode }}"

- name: "config: Create directory {{ leutils_config_LEROOT }}/live"
  file:
    state: "directory"
    path: "{{ leutils_config_LEROOT }}/live"
    owner: "{{ leutils_owner }}"
    group: "{{ leutils_group }}"
    mode: "{{ leutils_LEROOT_live_mode }}"

# EOF
...
