---

- name: "Config: Create configuration in {{ leutils_config_file }}"
  ansible.builtin.lineinfile:
    dest: "{{ leutils_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: "{{ leutils_owner }}"
    group: "{{ leutils_group }}"
    mode: "{{ leutils_config_mode }}"
    backup: "{{ leutils_backup_conf }}"
    create: true
  loop: "{{ leutils_config_items }}"

- name: "Config: Create directory {{ leutils_config_leroot }}"
  ansible.builtin.file:
    state: directory
    path: "{{ leutils_config_leroot }}"
    owner: "{{ leutils_owner }}"
    group: "{{ leutils_group }}"
    mode: "{{ leutils_leroot_mode }}"

- name: "Config: Create directory {{ leutils_config_leroot ~ '/live' }}"
  ansible.builtin.file:
    state: directory
    path: "{{ leutils_config_leroot }}/live"
    owner: "{{ leutils_owner }}"
    group: "{{ leutils_group }}"
    mode: "{{ leutils_leroot_live_mode }}"

# EOF
