---

- name: "copy: Test presence of {{ leutils_source_dest }}/le-utils-current.lock"
  stat:
    path: "{{ leutils_source_dest }}/le-utils-current.lock"
  register: leutils_lock

- debug:
    msg: "copy: [LOCK] le-utils-current.lock file is present.
          Scripts will not be copied."
  when:
    - leutils_lock.stat.exists
    - not leutils_ignore_lock|bool
    - leutils_debug|bool

- name: "copy: Create directory for installation {{ leutils_bin_dir }}"
  file:
    state: directory
    path: "{{ leutils_bin_dir }}"
    owner: "{{ leutils_owner }}"
    group: "{{ leutils_group }}"
    mode: "{{ leutils_bin_dir_mode }}"

- name: "copy: Copy scripts to {{ leutils_bin_dir }}"
  copy:
    src: "{{ leutils_source_dest }}/le-utils/{{ item }}"
    dest: "{{ leutils_bin_dir }}/{{ item }}"
    owner: "{{ leutils_owner }}"
    group: "{{ leutils_group }}"
    mode: "{{ leutils_bin_mode }}"
    remote_src: true
  loop:
    - lectl
    - leinfo
  when: (not ansible_check_mode) and
       ((not leutils_lock.stat.exists) or leutils_ignore_lock|bool)

# EOF
...
