---

- name: Test presence of {{leutils_source_dest}}/le-utils-current.lock
  stat: path="{{leutils_source_dest}}/le-utils-current.lock"
  register: le_utils_current_lock

- debug: msg="[LOCK] le-utils-current.lock file is present. Scripts will no be copied."
  when: le_utils_current_lock.stat.exists == True

- name: Create directory for installation {{leutils_bin_dir}}
  file: >
    state="directory"
    path="{{leutils_bin_dir}}"
    owner="{{leutils_owner}}"
    group="{{leutils_group}}"
    mode="{{leutils_bin_dir_mode}}"
  when: le_utils_current_lock.stat.exists == False

- name: Copy scripts to {{leutils_bin_dir}}
  copy: >
    src="{{leutils_source_dest}}/le-utils/{{item}}"
    dest="{{leutils_bin_dir}}/{{item}}"
    remote_src="yes"
    owner="{{leutils_owner}}"
    group="{{leutils_group}}"
    mode="{{leutils_bin_mode}}"
  with_items:
    - lectl
    - leinfo
  when: le_utils_current_lock.stat.exists == False

# EOF
...
