---

- name: Create directory for installation {{leutils_bin_dir}}
  file: >
    state="directory"
    path="{{leutils_bin_dir}}"
    owner="{{leutils_owner}}"
    group="{{leutils_group}}"
    mode="{{leutils_bin_dir_mode}}"

- name: Copy scripts to {{leutils_bin_dir}}
  copy: >
    src="{{leutils_source_dest}}/le-utils/{{item}}"
    dest="{{leutils_bin_dir}}/{{item}}"
    remote_src="yes"
    owner="{{leutils_owner}}"
    group="{{leutils_group}}"
    mode="{{leutils_bin_mode}}"
  with_items:
    - lectl
    - leinfo

# EOF
...
