---

- name: Create directory for installation {{leutils_bin_dir}}
  file: >
    state="directory"
    path="{{leutils_bin_dir}}"

- name: Copy scripts to {{leutils_bin_dir}}
  copy: >
    src="{{leutils_source_dest}}/le-utils/{{item}}"
    dest="{{leutils_bin_dir}}/{{item}}"
    remote_src="yes"
    owner="root"
    group="wheel"
    mode="0755"
  with_items:
    - lectl
    - leinfo

# EOF
...
