---

- name: Test presence of {{leutils_source_dest}}/le-utils-current.lock
  stat: path="{{leutils_source_dest}}/le-utils-current.lock"
  register: leutils_current_lock

- debug: msg="[LOCK] le-utils-current.lock file is present. Scripts will no be copied."
  when: leutils_current_lock.stat.exists == True and
        leutils_source_ignore_current_lock == "no"

- name: Create directory for installation {{leutils_bin_dir}}
  file: >
    state="directory"
    path="{{leutils_bin_dir}}"
    owner="{{leutils_owner}}"
    group="{{leutils_group}}"
    mode="{{leutils_bin_dir_mode}}"
  when: leutils_current_lock.stat.exists == False or
        leutils_source_ignore_current_lock == "yes"

- name: Copy scripts to {{leutils_bin_dir}}
  copy: >
    src="{{leutils_source_dest}}/le-utils/{{item}}"
    dest="{{leutils_bin_dir}}/{{item}}"
    remote_src="yes"
    owner="{{leutils_owner}}"
    group="{{leutils_group}}"
    mode="{{leutils_bin_mode}}"
  with_items:
    - lectl
    - leinfo
  when: leutils_current_lock.stat.exists == False or
        leutils_source_ignore_current_lock == "yes"

- name: Which bash
  command: "which bash"
  register: leutils_which_bash
  changed_when: false

  #- debug: msg="{{leutils_which_bash.stdout}}"

- name: Patch {{leutils_which_bash.stdout}}
  lineinfile: >
    dest="{{leutils_bin_dir}}/{{item}}"
    regexp="#!"
    line="#!{{leutils_which_bash.stdout}}"
  with_items:
    - lectl
    - leinfo

# EOF
...
