---

- name: Test lock file
  when: not leutils_ignore_lock | bool
  block:

    - name: "Copy: Test presence of {{ leutils_source_dest ~ '/le-utils-current.lock' }}"
      ansible.builtin.stat:
        path: "{{ leutils_source_dest }}/le-utils-current.lock"
      register: leutils_lock

    - name: "Copy: Debug le-utils-current.lock leutils_debug={{ leutils_debug }}"
      ansible.builtin.debug:
        msg: |
          [LOCK] le-utils-current.lock file is present. Scripts will not be copied.
      when:
        - leutils_lock.stat.exists
        - leutils_debug | bool

- name: Copy scripts
  when: not leutils_lock.stat.exists or leutils_ignore_lock | bool
  block:
    - name: "Copy: Create directory for installation {{ leutils_bin_dir }}"
      ansible.builtin.file:
        state: directory
        path: "{{ leutils_bin_dir }}"
        owner: "{{ leutils_owner }}"
        group: "{{ leutils_group }}"
        mode: "{{ leutils_bin_dir_mode }}"

    - name: "Copy: Copy scripts to {{ leutils_bin_dir }}"
      ansible.builtin.copy:
        src: "{{ leutils_source_dest }}/le-utils/{{ item }}"
        dest: "{{ leutils_bin_dir }}/{{ item }}"
        owner: "{{ leutils_owner }}"
        group: "{{ leutils_group }}"
        mode: "{{ leutils_bin_mode }}"
        remote_src: true
      loop:
        - lectl
        - leinfo

# EOF
