---

- name: "cron: Configure cron MAILTO={{ leutils_cron_mailto }}"
  community.general.cronvar:
    name: MAILTO
    value: "{{ leutils_cron_mailto }}"
    user: "{{ leutils_cron_user }}"

- name: "cron: Configure cron check expiry of certificates"
  ansible.builtin.cron:
    name: check expiry of certificates
    minute: "{{ leutils_days_cron_minute }}"
    hour: "{{ leutils_days_cron_hour }}"
    job: "{{ leutils_list_command }}"
    user: "{{ leutils_cron_user }}"
  when: leutils_days_enable|bool

- name: "cron: Configure cron dry-run renewal of certificates"
  ansible.builtin.cron:
    name: dry-run renewal of certificates
    minute: "{{ leutils_dryrun_cron_minute }}"
    hour: "{{ leutils_dryrun_cron_hour }}"
    job: "{{ leutils_dryrun_command }}"
    user: "{{ leutils_cron_user }}"
  when: leutils_dryrun|bool

- name: "cron: Create script to renew certificates"
  ansible.builtin.template:
    src: renew-certificates.j2
    dest: "{{ leutils_bin_dir }}/renew-certificates.sh"
    owner: "{{ leutils_owner }}"
    group: "{{ leutils_group }}"
    mode: "{{ leutils_bin_mode }}"
    backup: "{{ leutils_backup_conf }}"

- name: "cron: Configure cron renewal of certificates"
  ansible.builtin.cron:
    name: renewal of certificates
    minute: "{{ leutils_renew_cron_minute }}"
    hour: "{{ leutils_renew_cron_hour }}"
    job: "{{ leutils_renew_command }}"
    user: "{{ leutils_cron_user }}"
  when: leutils_renew|bool

# EOF
...
