---

- name: Configure cron MAILTO="{{leutils_cron_mailto}}"
  cronvar: name="MAILTO"
           value="\"{{leutils_cron_mailto}}\""
           user="{{leutils_cron_user}}"

- name: Configure cron check expiry of certificates
  cron: name="check expiry of certificates"
        minute="{{leutils_days_cron_minute}}"
        hour="{{leutils_days_cron_hour}}"
        job="/root/bin/lectl -e --Days={{leutils_days}} -a"
        user="{{leutils_cron_user}}"

- name: Configure cron dry-run renewal of certificates
  cron: name="dry-run renewal of certificates"
        minute="{{leutils_dryrun_cron_minute}}"
        hour="{{leutils_dryrun_cron_hour}}"
        job="/root/bin/lectl -n -c -a"
        user="{{leutils_cron_user}}"
  when: leutils_dryrun == "yes"
