---

- name: "cron: Configure cron MAILTO={{ leutils_cron_mailto }}"
  cronvar:
    name: "MAILTO"
    value: "{{ leutils_cron_mailto }}"
    user: "{{ leutils_cron_user }}"

- name: "cron: Configure cron check expiry of certificates"
  cron:
    name: "check expiry of certificates"
    minute: "{{ leutils_days_cron_minute }}"
    hour: "{{ leutils_days_cron_hour }}"
    job: "{{ leutils_list_command }}"
    user: "{{ leutils_cron_user }}"
  when: leutils_days_enable

- name: "cron: Configure cron dry-run renewal of certificates"
  cron:
    name: "dry-run renewal of certificates"
    minute: "{{ leutils_dryrun_cron_minute }}"
    hour: "{{ leutils_dryrun_cron_hour }}"
    job: "{{ leutils_dryrun_command }}"
    user: "{{ leutils_cron_user }}"
  when: leutils_dryrun

- name: "cron: Create script to renew certificates"
  template:
    src: "renew-certificates.j2"
    dest: "{{ leutils_bin_dir }}/renew-certificates.sh"
    owner: "{{ leutils_owner }}"
    group: "{{ leutils_group }}"
    mode: "{{ leutils_bin_mode }}"
    backup: yes
  when: leutils_renew

- name: "cron: Configure cron renewal of certificates"
  cron:
    name: "renewal of certificates"
    minute: "{{ leutils_renew_cron_minute }}"
    hour: "{{ leutils_renew_cron_hour }}"
    job: "{{ leutils_renew_command }}"
    user: "{{ leutils_cron_user }}"
  when: leutils_renew
  
# EOF
...
