---

- name: Debug leutils.
  vars:
    msg: |
         ansible_architecture [{{ ansible_architecture }}]
         ansible_os_family [{{ ansible_os_family }}]
         ansible_distribution [{{ ansible_distribution }}]
         ansible_distribution_major_version [{{ ansible_distribution_major_version }}]
         ansible_distribution_version [{{ ansible_distribution_version }}]
         ansible_distribution_release [{{ ansible_distribution_release }}]

         leutils_backup_conf [{{ leutils_backup_conf }}]
         leutils_days [{{ leutils_days }}]
         leutils_days_enable [{{ leutils_days_enable }}]
         leutils_list_command [{{ leutils_list_command }}]
         leutils_dryrun [{{ leutils_dryrun }}]
         leutils_dryrun_command [{{ leutils_dryrun_command }}]
         leutils_renew [{{ leutils_renew }}]
         leutils_renew_command [{{ leutils_renew_command }}]
         leutils_ignore_lock [{{ leutils_ignore_lock }}]
         leutils_source_version [{{ leutils_source_version }}]
         leutils_unarchive_extra_opts [{{ leutils_unarchive_extra_opts }}]
         leutils_config_file [{{ leutils_config_file }}]
         leutils_config_WEBSERVER [{{ leutils_config_WEBSERVER }}]
         leutils_config_LEROOT [{{ leutils_config_LEROOT }}]
         leutils_config_LEROOTMTIMEPRESERVE
         [{{ leutils_config_LEROOTMTIMEPRESERVE }}]
         leutils_config_FINGERPRINTFILE [{{ leutils_config_FINGERPRINTFILE }}]
         leutils_fingerprint [{{ leutils_fingerprint }}]
         leutils_fingerprint_command [{{ leutils_fingerprint_command }}]
         leutils_packages
         {{ leutils_packages | to_nice_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
