---

- name: "fingerprint: Create {{ leutils_config_FINGERPRINTFILE }}"
  command: "{{ leutils_fingerprint_command }}"
  changed_when: False
  when: leutils_fingerprint

# TODO: Make idempotent. With checksum?

# EOF
...
