---

- name: "fingerprint: Create {{ leutils_config_FINGERPRINTFILE }}"
  command: "{{ leutils_fingerprint_command }}"
  changed_when: false
  when: leutils_fingerprint|bool

# TODO: Make idempotent. With checksum?

# EOF
...
