---

- include: packages.yml
  tags: leutils_packages

- include: source.yml
  tags: leutils_source

- include: config.yml
  tags: leutils_config

- include: copy.yml
  tags: leutils_copy

- include: fingerprint.yml
  tags: leutils_fingerprint

- include: cron.yml
  tags: leutils_cron

# EOF
...
