---

- include: packages.yml
  tags:
    - leutils_packages
    - leutils_all

- include: source.yml
  tags:
    - leutils_source
    - leutils_all

- include: copy.yml
  tags:
    - leutils_copy
    - leutils_all

- include: cron.yml
  tags:
    - leutils_cron
    - leutils_all

# EOF
...
