---

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: leutils_debug | bool
  tags: leutils_debug

- name: Import pkg.yml
  ansible.builtin.import_tasks: pkg.yml
  when: leutils_install | bool
  tags: leutils_pkg

- name: Import source.yml
  ansible.builtin.import_tasks: source.yml
  tags: leutils_source

- name: Import config.yml
  ansible.builtin.import_tasks: config.yml
  tags: leutils_config

- name: Import copy.yml
  ansible.builtin.import_tasks: copy.yml
  tags: leutils_copy

- name: Import fingerprint.yml
  ansible.builtin.import_tasks: fingerprint.yml
  tags: leutils_fingerprint

- name: Import cron.yml
  ansible.builtin.import_tasks: cron.yml
  tags: leutils_cron

# EOF
