---

- include: packages.yml
  tags:
    - leutils-packages
    - leutils

- include: source.yml
  tags:
    - leutils-source
    - leutils

- include: copy.yml
  tags:
    - leutils-copy
    - leutils

- include: cron.yml
  tags:
    - leutils-configure
    - leutils
