---

- import_tasks: debug.yml
  when: leutils_debug
  tags: [leutils_debug, always]

- import_tasks: packages.yml
  tags: leutils_packages

- import_tasks: source.yml
  tags: leutils_source

- import_tasks: config.yml
  tags: leutils_config

- import_tasks: copy.yml
  tags: leutils_copy

- import_tasks: fingerprint.yml
  tags: leutils_fingerprint

- import_tasks: cron.yml
  tags: leutils_cron

# EOF
...
