---

- name: "Pkg: Install FreeBSD packages"
  when: freebsd_install_method | lower == "packages"
  register: result
  community.general.pkgng:
    name: "{{ leutils_packages }}"
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"

- name: "Pkg: Install FreeBSD ports"
  when: freebsd_install_method | lower == "ports"
  register: result
  community.general.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ leutils_packages }}"
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"

# EOF
